(function(){
  function initEssay(){
    const D=window.ENCCEJA_ESSAY_TOPICS,sec=document.getElementById('essay');if(!D||!D.length||!sec)return false;
    let current=parseInt(localStorage.getItem('encceja-redacao-atual')||'0',10);if(!Number.isInteger(current)||current<0||current>=D.length)current=0;
    sec.innerHTML=`<h2>✍️ Redação</h2><p>Escolha um tema, escreva sua redação e depois consulte o modelo de treino alinhado às cinco competências do ENCCEJA.</p><div class="card"><b>🔎 Escolher tema</b><input id="essaySearch" type="search" placeholder="Pesquisar entre os 100 temas..." autocomplete="off"><select id="essaySelect" aria-label="Selecionar tema de redação"></select><button id="essayRandom" type="button" class="primary">🎲 Sortear tema</button></div><div id="essayStatus" class="card"></div><div id="essayPrompt" class="card"></div><textarea id="essayText" rows="14" placeholder="Escreva aqui sua redação..."></textarea><button id="essaySave" type="button" class="primary">💾 Salvar redação</button><button id="essayModelButton" type="button" class="secondary">📘 Mostrar resposta-modelo</button><div id="essayModel" class="card hidden"></div><div id="essayPoints" class="card"></div>`;
    const search=essaySearch,select=essaySelect,text=essayText,status=essayStatus,prompt=essayPrompt,model=essayModel,points=essayPoints,modelButton=essayModelButton;
    function fillSelect(filter){const f=(filter||'').trim().toLowerCase();select.innerHTML='';D.forEach((x,i)=>{if(f&&!x.t.toLowerCase().includes(f))return;const o=document.createElement('option');o.value=String(i);o.textContent=(i+1)+'. '+x.t;select.appendChild(o)});const wanted=[...select.options].find(o=>Number(o.value)===current);if(wanted)select.value=String(current);else if(select.options.length)select.selectedIndex=0}
    function esc(s){return String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}
    function openTopic(i,origin){i=Number(i);if(!Number.isInteger(i)||i<0||i>=D.length)return;current=i;localStorage.setItem('encceja-redacao-atual',String(i));const x=D[i];prompt.innerHTML='<b>Tema '+(i+1)+'</b><h3>'+esc(x.t)+'</h3><p>'+esc(x.p)+'</p>';text.value=localStorage.getItem('encceja-redacao-'+(i+1))||'';model.innerHTML='<h3>📘 Resposta-modelo de treino</h3>'+x.m.split('\n\n').map(p=>'<p>'+esc(p)+'</p>').join('')+'<small>Este é um exemplo didático, não uma redação oficial nem uma garantia de nota.</small>';model.classList.add('hidden');modelButton.textContent='📘 Mostrar resposta-modelo';points.innerHTML='<b>✅ Padrão de avaliação do ENCCEJA</b><ul>'+x.k.map(v=>'<li>'+esc(v)+'</li>').join('')+'</ul><p class="small">'+esc(x.score||'')+'</p>';status.textContent=(origin==='random'?'Tema sorteado: ':'Tema selecionado: ')+(i+1)+'. '+x.t;fillSelect(search.value);if([...select.options].some(o=>Number(o.value)===i))select.value=String(i)}
    search.addEventListener('input',()=>fillSelect(search.value));select.addEventListener('change',()=>openTopic(select.value,'manual'));select.addEventListener('click',()=>{if(select.value!=='')openTopic(select.value,'manual')});essayRandom.addEventListener('click',()=>{let used=[];try{used=JSON.parse(localStorage.getItem('encceja-redacao-sorteados')||'[]')}catch(e){}if(!Array.isArray(used)||used.length>=D.length)used=[];const pool=D.map((_,i)=>i).filter(i=>!used.includes(i)),i=pool[Math.floor(Math.random()*pool.length)];used.push(i);localStorage.setItem('encceja-redacao-sorteados',JSON.stringify(used));search.value='';fillSelect('');openTopic(i,'random')});function saveText(){localStorage.setItem('encceja-redacao-'+(current+1),text.value)}text.addEventListener('input',saveText);essaySave.addEventListener('click',()=>{saveText();status.textContent='✅ Redação do tema '+(current+1)+' salva neste aparelho.'});modelButton.addEventListener('click',()=>{const hidden=model.classList.toggle('hidden');modelButton.textContent=hidden?'📘 Mostrar resposta-modelo':'📕 Ocultar resposta-modelo';if(!hidden)model.scrollIntoView({block:'nearest',behavior:'smooth'})});fillSelect('');openTopic(current,'manual');return true}
  let tries=0;const timer=setInterval(()=>{tries++;if(initEssay()||tries>120)clearInterval(timer)},50)
})();
