(function(){
const MATERIAS=[1,2,3,4].map(i=>window['ENCCEJA_READING_PART_'+i]).filter(Boolean);
function show(mi,ai){const m=MATERIAS[mi],a=m&&m.aulas[ai],v=document.getElementById('readingBody');if(!v||!a)return;v.innerHTML='<div class="card"><small>'+m.nome+' • '+a.n+'</small><h2>'+a.t+'</h2>'+a.html+'</div>';document.querySelectorAll('.readingLesson').forEach(b=>b.classList.remove('on'));const b=document.querySelector('[data-read="'+mi+'-'+ai+'"]');if(b)b.classList.add('on');localStorage.setItem('encceja-reading-last',mi+'-'+ai);v.scrollIntoView({block:'start'})}
function init(){if(document.getElementById('reading'))return true;const app=document.querySelector('.app'),nav=app&&app.querySelector('nav');if(!app||!nav||!MATERIAS.length)return false;const style=document.createElement('style');style.textContent='.readingLesson{width:100%;padding:12px;margin:6px 0;text-align:left;border:1px solid #24517c;border-radius:12px;background:#07182e;color:#fff}.readingLesson.on{border-color:#ffd52e}.readingText{line-height:1.65}.readingText h3{color:#ffd52e}.readingText p{color:#e7eef7;font-size:17px}.readingSubject{margin-bottom:10px}.readingSubject summary{cursor:pointer;padding:6px 0}nav{overflow-x:auto;justify-content:flex-start}nav button{min-width:74px;flex:1}';document.head.appendChild(style);const sec=document.createElement('section');sec.id='reading';sec.className='panel hidden';sec.innerHTML='<h2>📖 Leitura</h2><p>Resumos das aulas fornecidas, organizados por matéria.</p><div id="readingSubjects"></div><div id="readingBody" class="readingText"></div>';app.insertBefore(sec,nav);const root=sec.querySelector('#readingSubjects');MATERIAS.forEach((m,mi)=>{const d=document.createElement('details');d.className='card readingSubject';if(mi===0)d.open=true;d.innerHTML='<summary><b>'+m.nome+'</b> <small>('+m.aulas.length+' aulas)</small></summary><div></div>';const list=d.querySelector('div');m.aulas.forEach((a,ai)=>{const b=document.createElement('button');b.className='readingLesson';b.dataset.read=mi+'-'+ai;b.innerHTML='<b>'+a.n+'</b><br><small>'+a.t+'</small>';b.onclick=()=>show(mi,ai);list.appendChild(b)});root.appendChild(d)});
const b=document.createElement('button');b.id='nreading';b.innerHTML='📖<br>Leitura';b.onclick=function(){document.querySelectorAll('.app>main,.app>section').forEach(e=>e.classList.add('hidden'));const ff=document.getElementById('feedFilter');if(ff)ff.classList.add('hidden');nav.querySelectorAll('button').forEach(x=>x.classList.remove('on'));sec.classList.remove('hidden');b.classList.add('on');let p=(localStorage.getItem('encceja-reading-last')||'0-0').split('-').map(Number);if(!MATERIAS[p[0]]||!MATERIAS[p[0]].aulas[p[1]])p=[0,0];show(p[0],p[1])};nav.insertBefore(b,nav.lastElementChild);
const e=document.createElement('button');e.id='nessay';e.innerHTML='✍️<br>Redação';e.onclick=function(){if(typeof tab==='function')tab('essay');nav.querySelectorAll('button').forEach(x=>x.classList.remove('on'));e.classList.add('on');sec.classList.add('hidden')};nav.insertBefore(e,nav.lastElementChild);
nav.querySelectorAll('button:not(#nreading):not(#nessay)').forEach(x=>x.addEventListener('click',()=>sec.classList.add('hidden')));return true}
let n=0,t=setInterval(()=>{n++;if(init()||n>120)clearInterval(t)},50);
function loadScript(src,next){const s=document.createElement('script');s.src=src;s.onload=next||null;document.body.appendChild(s)}
loadScript('essay-data.js?v=3',()=>loadScript('essay.js?v=3'));
})();